In [180]:
from sklearn.linear_model import LinearRegression

In [181]:
model = LinearRegression()

In [182]:
import numpy as np
import pandas as pd
import seaborn as sns

In [183]:
acao = pd.read_csv("./ITSA4.SA.csv")

Vamos conhecer um pouco melhor o conjunto de dados.

In [184]:
acao.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  2021-09-28  10.628571  10.876190  10.476190  10.504761   9.887136  68329905
1  2021-09-29  10.590476  10.761904  10.495238  10.704761  10.075378  50039955
2  2021-09-30  10.780952  10.809523  10.571428  10.609523   9.985741  56119140
3  2021-10-01  10.704761  10.923809  10.628571  10.876190  10.236730  37974195
4  2021-10-04  10.828571  10.876190  10.533333  10.628571  10.003667  36064245

In [185]:
acao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       251 non-null    object 
 1   Open       251 non-null    float64
 2   High       251 non-null    float64
 3   Low        251 non-null    float64
 4   Close      251 non-null    float64
 5   Adj Close  251 non-null    float64
 6   Volume     251 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.9+ KB


In [186]:
acao.describe().T

count          mean           std           min           25%  \
Open       251.0  9.550937e+00  6.732740e-01  8.070000e+00  9.145000e+00   
High       251.0  9.650100e+00  6.780125e-01  8.170000e+00  9.219524e+00   
Low        251.0  9.439380e+00  6.580235e-01  7.960000e+00  9.048333e+00   
Close      251.0  9.541318e+00  6.701330e-01  8.100000e+00  9.130000e+00   
Adj Close  251.0  9.313353e+00  6.086180e-01  8.028399e+00  8.825364e+00   
Volume     251.0  2.529521e+07  1.094661e+07  4.922600e+06  1.697070e+07   

                    50%           75%           max  
Open       9.457142e+00  1.000952e+01  1.090000e+01  
High       9.550000e+00  1.013643e+01  1.100000e+01  
Low        9.370000e+00  9.910000e+00  1.081000e+01  
Close      9.460000e+00  1.002429e+01  1.092000e+01  
Adj Close  9.296033e+00  9.777211e+00  1.072770e+01  
Volume     2.373500e+07  3.017865e+07  7.448060e+07

In [187]:
acao.drop(["Close", "Volume"], axis=1).describe()

Open        High         Low   Adj Close
count  251.000000  251.000000  251.000000  251.000000
mean     9.550937    9.650100    9.439380    9.313353
std      0.673274    0.678012    0.658024    0.608618
min      8.070000    8.170000    7.960000    8.028399
25%      9.145000    9.219524    9.048333    8.825364
50%      9.457142    9.550000    9.370000    9.296033
75%     10.009524   10.136429    9.910000    9.777211
max     10.900000   11.000000   10.810000   10.727704

In [188]:
data = acao[["Close", "Volume"]]

In [224]:
data.describe()

Close        Volume
count  251.000000  2.510000e+02
mean     9.541318  2.529521e+07
std      0.670133  1.094661e+07
min      8.100000  4.922600e+06
25%      9.130000  1.697070e+07
50%      9.460000  2.373500e+07
75%     10.024285  3.017865e+07
max     10.920000  7.448060e+07

### **2.2. Treino / Teste** 

In [190]:
from sklearn.model_selection import train_test_split

In [191]:
X = data['Close']
Y = data['Volume']

In [192]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=50)

In [193]:
x_train.head()

74      9.54
208     8.63
96     10.58
72      9.56
69      9.18
Name: Close, dtype: float64

In [194]:
y_train.head()

74     14593300
208    20172100
96     25694400
72     41082300
69     21680100
Name: Volume, dtype: int64

In [195]:
x_test.head()

82      9.97
108     9.53
207     8.65
136    10.16
63      8.93
Name: Close, dtype: float64

In [196]:
x_test.shape

(63,)

 - **Variável resposta (target)**

In [197]:
y_train.head()

74     14593300
208    20172100
96     25694400
72     41082300
69     21680100
Name: Volume, dtype: int64

In [198]:
y_train.shape

(188,)

In [199]:
y_test.head()

82     21536900
108    30182700
207    14652600
136    13150900
63     23322800
Name: Volume, dtype: int64

In [200]:
from sklearn.preprocessing import MinMaxScaler

In [201]:
# scaler = MinMaxScaler().fit(x_train)

In [202]:
x_train

74      9.54000
208     8.63000
96     10.58000
72      9.56000
69      9.18000
         ...   
33      9.55238
109    10.04000
139     9.91000
224     9.32000
176     8.72000
Name: Close, Length: 188, dtype: float64

In [203]:
y_train

74     14593300
208    20172100
96     25694400
72     41082300
69     21680100
         ...   
33     29892975
109    49616300
139    21183400
224    28733800
176    14858000
Name: Volume, Length: 188, dtype: int64

In [204]:
y_train =pd.DataFrame(y_train)
x_train =pd.DataFrame(x_train)

In [205]:
scaler = MinMaxScaler().fit(x_train)
x_train_scaler =scaler.transform(x_train)

scaler = MinMaxScaler().fit(y_train)
y_train_scaler =scaler.transform(y_train)


# scaler = MinMaxScaler().fit(x_test)
# x_teste_scaler =scaler.transform(x_test)

# scaler = MinMaxScaler().fit(y_test)
# y_teste_scaler =scaler.transform(y_test)

In [206]:
x_train, x_test, y_train, y_test = train_test_split(x_train_scaler, y_train_scaler, test_size=0.25, random_state=50)

In [207]:
y_train

array([[0.35560252],
       [0.09658415],
       [0.13217459],
       [0.4477076 ],
       [0.14683286],
       [0.19708157],
       [0.92364178],
       [0.14991374],
       [0.3463501 ],
       [0.45977026],
       [0.23377325],
       [0.37229075],
       [0.36905043],
       [0.10846632],
       [0.44314579],
       [0.52857759],
       [0.47650019],
       [0.6425386 ],
       [0.26410025],
       [0.11465971],
       [0.44317404],
       [0.47035711],
       [0.5388841 ],
       [0.30083527],
       [0.21129273],
       [0.33605624],
       [0.51984962],
       [0.18078438],
       [0.1968573 ],
       [0.40825498],
       [0.3196426 ],
       [0.30083527],
       [0.31417896],
       [0.47611921],
       [0.07907789],
       [0.29425372],
       [0.34029874],
       [0.26902585],
       [0.07921447],
       [0.24705282],
       [0.36286121],
       [0.31811582],
       [0.44738154],
       [0.20062682],
       [0.36303516],
       [0.13915869],
       [0.16589896],
       [0.134

In [208]:
y_train_scaler

array([[0.13903074],
       [0.21923431],
       [0.29862561],
       [0.51984962],
       [0.24091406],
       [0.27319791],
       [0.11887777],
       [0.31417896],
       [0.15249288],
       [0.2206197 ],
       [0.56033957],
       [0.34029874],
       [0.30589616],
       [0.47516598],
       [0.44314579],
       [0.27045631],
       [0.12400443],
       [0.24705282],
       [0.31811582],
       [0.15919664],
       [0.17395411],
       [0.33605624],
       [0.11014118],
       [0.40926852],
       [0.17730383],
       [0.30366744],
       [0.        ],
       [0.25844044],
       [0.16745737],
       [0.28784324],
       [0.15205584],
       [0.19378361],
       [0.22927916],
       [0.4772377 ],
       [0.28481555],
       [0.24684026],
       [0.16977918],
       [0.11236522],
       [0.21775497],
       [0.1151557 ],
       [0.43062121],
       [0.30083527],
       [0.36286121],
       [0.11701602],
       [0.18706547],
       [0.43965468],
       [0.26902585],
       [0.282

In [209]:
model = model.fit(x_train, y_train)

In [210]:
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'n_features_in_': 1,
 'coef_': array([[0.13711]]),
 'rank_': 1,
 'singular_': array([2.71211016]),
 'intercept_': array([0.22570502])}

In [211]:
a = model.coef_
print(a)

[[0.13711]]


In [221]:
b = model.intercept_
print(b)

[0.22570502]


In [213]:

y_test[2]

array([0.13539909])

In [214]:
x_test[1]

array([0.49476525])

In [223]:
ia_ac1 = model.predict(x_test)

print(ia_ac1[0], y_test[0])

[0.23299811] [0.17395411]


In [216]:
float(y_test[0])

0.17395411023893728

In [217]:
lista_pre = []

for i in range(len(ia_ac1)):
        lista_pre.append({"vlr_original": float(y_test[i]), "vlr_Previsto": float(ia_ac1[i])})

lista_pre

[{'vlr_original': 0.17395411023893728, 'vlr_Previsto': 0.23299810739634516},
 {'vlr_original': 0.2815111849104345, 'vlr_Previsto': 0.2935422855141593},
 {'vlr_original': 0.13539909140573334, 'vlr_Previsto': 0.2810398469492029},
 {'vlr_original': 0.11515569740360562, 'vlr_Previsto': 0.2509877173372489},
 {'vlr_original': 0.30366744299721093, 'vlr_Previsto': 0.31419445496745163},
 {'vlr_original': 0.3116897409356221, 'vlr_Previsto': 0.2903008981467802},
 {'vlr_original': 0.07463843123724087, 'vlr_Previsto': 0.24709807194462108},
 {'vlr_original': 0.13726242847695447, 'vlr_Previsto': 0.28161867480419334},
 {'vlr_original': 0.22549850484487763, 'vlr_Previsto': 0.2801137223812182},
 {'vlr_original': 0.4005030334397194, 'vlr_Previsto': 0.2773353972978316},
 {'vlr_original': 0.4079420052330429, 'vlr_Previsto': 0.3065077377425404},
 {'vlr_original': 0.1026553379913166, 'vlr_Previsto': 0.2689773272781528},
 {'vlr_original': 0.1524928836366773, 'vlr_Previsto': 0.23348431307042364},
 {'vlr_origin

In [218]:


df1 = pd.DataFrame(y_test, columns=["test_y"])
df2 = pd.DataFrame(lista_pre)
inte = 2
# df2['desv'] = df2['vlr_Previsto'] + (inte * df2['vlr_Previsto'].std())
# df2['desv-'] = df2['vlr_Previsto'] - (inte * df2['vlr_Previsto'].std())



In [219]:
df2

vlr_original  vlr_Previsto
0       0.173954      0.232998
1       0.281511      0.293542
2       0.135399      0.281040
3       0.115156      0.250988
4       0.303667      0.314194
5       0.311690      0.290301
6       0.074638      0.247098
7       0.137262      0.281619
8       0.225499      0.280114
9       0.400503      0.277335
10      0.407942      0.306508
11      0.102655      0.268977
12      0.152493      0.233484
13      0.305896      0.296784
14      0.314802      0.296205
15      0.290466      0.317598
16      0.177304      0.260712
17      0.204669      0.289884
18      0.337024      0.317112
19      0.229143      0.264601
20      0.395434      0.276872
21      0.237553      0.278215
22      0.215621      0.321974
23      0.317446      0.269464
24      0.736027      0.347719
25      0.294160      0.272867
26      0.284816      0.356517
27      0.372726      0.281040
28      0.409269      0.279674
29      0.358986      0.296321
30      0.253355      0.311763
31      0.430621      0.273631
32      0.277785      0.341422
33      0.839757      0.274326
34      0.217755      0.293288
35      0.505050      0.298150
36      0.337924      0.309819
37      0.204598      0.296691
38      0.201729      0.290857
39      0.400497      0.348183
40      0.475166      0.360685
41      0.605596      0.337069
42      0.219234      0.251474
43      0.301229      0.316695
44      0.282417      0.301877
45      0.339573      0.270436
46      0.124004      0.358925

In [220]:
import plotly.express as px

# df = px.data(df2)
fig = px.line(df2)
fig.show()